#!/usr/bin/env bash
# Conventional Commits validator. Invoked by .husky/commit-msg.
#
# Accepted shapes:
#   <type>(<scope>): <subject>
#   <type>: <subject>
#
# Types : feat | fix | chore | docs | refactor | test | ci | perf | build | revert
# Scopes: free-form lowercase token (a-z0-9-) — recommended: cli, extract, summary, docs, infra, hooks
# Subject: 1-72 chars, no trailing period.
#
# Special cases accepted without prefix:
#   - Initial commit lines starting with "Initial commit"
#   - Revert commits autogenerated by `git revert`
#   - Merge commits

set -euo pipefail

MSG_FILE="${1:?commit-msg path required}"
FIRST_LINE="$(head -n1 "$MSG_FILE")"

# Skip checks for merge / revert / fixup auto-prefixed commits.
case "$FIRST_LINE" in
  "Merge "*|"Revert "*|"fixup!"*|"squash!"*|"Initial commit"*) exit 0 ;;
esac

# Allow lines with trailing whitespace; trim for the regex check.
TRIMMED="$(printf '%s' "$FIRST_LINE" | sed -E 's/[[:space:]]+$//')"

PATTERN='^(feat|fix|chore|docs|refactor|test|ci|perf|build|revert)(\([a-z0-9-]+\))?: [^.].{0,70}[^.]$'

if ! [[ "$TRIMMED" =~ $PATTERN ]]; then
  cat <<EOF >&2
check-commit-msg: FAIL message does not match Conventional Commits shape.

Got: "$FIRST_LINE"

Required:
  <type>(<scope>): <subject>
or:
  <type>: <subject>

Where:
  type    = feat | fix | chore | docs | refactor | test | ci | perf | build | revert
  scope   = optional lowercase token (e.g. cli, extract, summary, docs, infra, hooks)
  subject = 1-72 chars, no trailing period

Examples:
  feat(extract): add nuclei-playbooks source
  fix(cli): preserve include filter when round-tripping sources.yaml
  docs: refresh CONFIGURATION.md after sources.yaml schema change
EOF
  exit 1
fi

echo "check-commit-msg: OK"
